# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bbapi

class RobotRole(object):
    NONE = 0
    STRIKER = 1
    DEFENDER = 2
    GOALKEEPER = 3
    SUPPORTER_DEFENSE = 4
    SUPPORTER_OFFENSE = 5
    SEARCHER = 6
    DEMO = 7
    PENALTYKICKER = 8
    PENALTYGOALIE = 9
    OBSTACLE_AVOIDER = 10
    PASSING_ROBOT = 11
