set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR i686)


set(CROSS_PREFIX  ${CTC_DIR}/gcc/bin/i686-bembelbots-linux-gnu-)

set(CMAKE_BUILD_RPATH ${CTC_DIR}/ctc-linux64-atom-2.8.5.10/yocto-sdk/sysroots/core2-32-sbr-linux/usr/lib)

# gcc
set(CMAKE_C_COMPILER    ${CROSS_PREFIX}gcc       CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER  ${CROSS_PREFIX}c++       CACHE FILEPATH "" FORCE)

# binutils
set(CMAKE_AR            ${CROSS_PREFIX}ar        CACHE FILEPATH "" FORCE)
set(CMAKE_LINKER        ${CROSS_PREFIX}ld        CACHE FILEPATH "" FORCE)
set(CMAKE_NM            ${CROSS_PREFIX}nm        CACHE FILEPATH "" FORCE)
set(CMAKE_OBJCOPY       ${CROSS_PREFIX}objcopy   CACHE FILEPATH "" FORCE)
set(CMAKE_OBJDUMP       ${CROSS_PREFIX}objdump   CACHE FILEPATH "" FORCE)
set(CMAKE_RANLIB        ${CROSS_PREFIX}ranlib    CACHE FILEPATH "" FORCE)
set(CMAKE_STRIP         ${CROSS_PREFIX}strip     CACHE FILEPATH "" FORCE)


set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
